#!/usr/bin/env python3
"""Hardware-faithful 5-station + 5-rover NTRIP integration simulator.

Running this file without arguments starts the complete demo preset that matches
the first five records generated by Database/Seeders/NtripDemoSeeder:

    python3 ntrip_full_flow_5x5.py

The zero-argument preset creates five ESP32-style base stations and exactly one
Raspberry-Pi-style rover for each corresponding public mountpoint. It exercises
the complete runtime path before deploying physical stations and rovers.

This tool simulates all runtime links used by the project:

1. ESP32 base telemetry:
   POST /api/v1/stations/{device_id}/telemetry

2. NTRIP Source:
   POST /{mountpoint}, followed by a continuous RTCM3 stream.

3. Raspberry Pi rover client (matching ntrip_cc/ntrip.cc):
   - HTTP/1.0 GET handshake.
   - Ntrip-Version: Ntrip/2.0.
   - User-Agent: NTRIP PiNtripBridge/1.0.
   - Optional Basic authentication.
   - TCP keepalive and TCP_NODELAY.
   - RTCM3 CRC24Q parsing and optional whitelist.
   - GGA every five seconds using fixed fallback coordinates.
   - Exponential reconnect delay: 1, 2, 4, 8, then 16 seconds.
   - Optional MAVLink 2 GPS_RTCM_DATA forwarding over UDP or serial.

The generated MSM4 payloads are deterministic transport test data. Use
--rtcm-file with a real ZED-F9P capture when validating an actual RTK solution.
No third-party Python package is required.
"""

from __future__ import annotations

import argparse
import base64
import json
import math
import os
import signal
import socket
import ssl
import struct
import sys
import termios
import threading
import time
import urllib.error
import urllib.request
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import quote


CRC24Q_POLYNOMIAL = 0x1864CFB
FIRMWARE_VERSION = "1.0.0-sim"
RTCM_FORMAT = "RTCM 3.3"

# Typical ZED-F9P base output set used by the project.
RTCM_PERIODS_S = {
    1005: 10.0,
    1074: 1.0,
    1084: 1.0,
    1094: 1.0,
    1124: 1.0,
    1230: 10.0,
}

# Payload sizes chosen to create a realistic RTCM upload bitrate for UI tests.
# Only type 1005 is fully encoded as a real reference-station message.
SYNTHETIC_PAYLOAD_BYTES = {
    1074: 180,
    1084: 165,
    1094: 165,
    1124: 165,
    1230: 8,
}

# These five profiles intentionally mirror profile(1..5) in
# Database/Seeders/NtripDemoSeeder. Keep both files synchronized.
DEFAULT_STATIONS = [
    {
        "device_id": "CTUAV-BASE-001",
        "token": "ctuav-base-001-development-token",
        "mountpoint": "CTUAV-RTCM-001",
        "network_type": "ethernet",
        "ip": "192.168.10.101",
        "latitude": 10.9801234,
        "longitude": 106.6745678,
        "altitude_m": 18.17,
        "station_id": 1,
    },
    {
        "device_id": "CTUAV-BASE-002",
        "token": "ctuav-base-002-development-token",
        "mountpoint": "CTUAV-RTCM-002",
        "network_type": "ethernet",
        "ip": "192.168.10.102",
        "latitude": 10.9805434,
        "longitude": 106.6765678,
        "altitude_m": 18.34,
        "station_id": 2,
    },
    {
        "device_id": "CTUAV-BASE-003",
        "token": "ctuav-base-003-development-token",
        "mountpoint": "CTUAV-RTCM-003",
        "network_type": "wifi",
        "ip": "192.168.10.103",
        "latitude": 10.9809634,
        "longitude": 106.6785678,
        "altitude_m": 18.51,
        "station_id": 3,
    },
    {
        "device_id": "CTUAV-BASE-004",
        "token": "ctuav-base-004-development-token",
        "mountpoint": "CTUAV-RTCM-004",
        "network_type": "ethernet",
        "ip": "192.168.10.104",
        "latitude": 10.9813834,
        "longitude": 106.6805678,
        "altitude_m": 18.68,
        "station_id": 4,
    },
    {
        "device_id": "CTUAV-BASE-005",
        "token": "ctuav-base-005-development-token",
        "mountpoint": "CTUAV-RTCM-005",
        "network_type": "ethernet",
        "ip": "192.168.10.105",
        "latitude": 10.9818034,
        "longitude": 106.6825678,
        "altitude_m": 18.85,
        "station_id": 5,
    },
]


def crc24q(data: bytes) -> int:
    """Calculate the RTCM3 CRC24Q checksum."""
    crc = 0

    for byte in data:
        crc ^= byte << 16

        for _ in range(8):
            crc <<= 1

            if crc & 0x1000000:
                crc ^= CRC24Q_POLYNOMIAL

    return crc & 0xFFFFFF


def rtcm_message_type(frame: bytes) -> int:
    """Return the 12-bit RTCM message number."""
    if len(frame) < 8 or frame[0] != 0xD3:
        return -1

    return (frame[3] << 4) | (frame[4] >> 4)


def build_rtcm_frame(payload: bytes) -> bytes:
    """Wrap a payload in an RTCM3 transport frame with CRC24Q."""
    payload_length = len(payload)

    if payload_length > 1023:
        raise ValueError("RTCM payload exceeds 1023 bytes.")

    header = bytes(
        (
            0xD3,
            (payload_length >> 8) & 0x03,
            payload_length & 0xFF,
        )
    )
    body = header + payload
    checksum = crc24q(body).to_bytes(3, "big")

    return body + checksum


class BitWriter:
    """Minimal MSB-first bit writer for RTCM payload construction."""

    def __init__(self) -> None:
        self._bits: list[int] = []

    def unsigned(self, value: int, width: int) -> None:
        if value < 0 or value >= (1 << width):
            raise ValueError(f"{value} does not fit in {width} unsigned bits.")

        for shift in range(width - 1, -1, -1):
            self._bits.append((value >> shift) & 1)

    def signed(self, value: int, width: int) -> None:
        minimum = -(1 << (width - 1))
        maximum = (1 << (width - 1)) - 1

        if not minimum <= value <= maximum:
            raise ValueError(f"{value} does not fit in {width} signed bits.")

        self.unsigned(value & ((1 << width) - 1), width)

    def to_bytes(self) -> bytes:
        while len(self._bits) % 8:
            self._bits.append(0)

        output = bytearray()

        for offset in range(0, len(self._bits), 8):
            value = 0

            for bit in self._bits[offset : offset + 8]:
                value = (value << 1) | bit

            output.append(value)

        return bytes(output)


def geodetic_to_ecef(
    latitude_deg: float,
    longitude_deg: float,
    altitude_m: float,
) -> tuple[float, float, float]:
    """Convert WGS84 latitude, longitude and altitude to ECEF metres."""
    semi_major_axis = 6378137.0
    inverse_flattening = 298.257223563
    flattening = 1.0 / inverse_flattening
    eccentricity_sq = flattening * (2.0 - flattening)

    latitude = math.radians(latitude_deg)
    longitude = math.radians(longitude_deg)

    sin_latitude = math.sin(latitude)
    cos_latitude = math.cos(latitude)
    prime_vertical = semi_major_axis / math.sqrt(
        1.0 - eccentricity_sq * sin_latitude * sin_latitude
    )

    x = (prime_vertical + altitude_m) * cos_latitude * math.cos(longitude)
    y = (prime_vertical + altitude_m) * cos_latitude * math.sin(longitude)
    z = (
        prime_vertical * (1.0 - eccentricity_sq) + altitude_m
    ) * sin_latitude

    return x, y, z


def build_type_1005(
    station_id: int,
    latitude: float,
    longitude: float,
    altitude_m: float,
) -> bytes:
    """Build a valid RTCM type 1005 fixed reference-station position."""
    x, y, z = geodetic_to_ecef(latitude, longitude, altitude_m)
    writer = BitWriter()

    writer.unsigned(1005, 12)
    writer.unsigned(station_id, 12)
    writer.unsigned(0, 6)   # ITRF realization year.
    writer.unsigned(1, 1)   # GPS indicator.
    writer.unsigned(1, 1)   # GLONASS indicator.
    writer.unsigned(1, 1)   # Galileo indicator.
    writer.unsigned(0, 1)   # Physical reference station indicator.
    writer.signed(round(x / 0.0001), 38)
    writer.unsigned(1, 1)   # Single receiver oscillator indicator.
    writer.unsigned(0, 1)   # Reserved.
    writer.signed(round(y / 0.0001), 38)
    writer.unsigned(0, 2)   # Quarter cycle indicator.
    writer.signed(round(z / 0.0001), 38)

    return build_rtcm_frame(writer.to_bytes())


def build_synthetic_rtcm_frame(
    message_type: int,
    station_id: int,
    sequence: int,
) -> bytes:
    """Build a deterministic CRC-valid test frame for one RTCM message type."""
    payload_size = SYNTHETIC_PAYLOAD_BYTES[message_type]
    payload = bytearray(payload_size)

    # RTCM payload starts with a 12-bit message number followed by a
    # 12-bit reference-station ID for the message set used here.
    payload[0] = (message_type >> 4) & 0xFF
    payload[1] = ((message_type & 0x0F) << 4) | ((station_id >> 8) & 0x0F)
    payload[2] = station_id & 0xFF

    # Fill the remaining payload deterministically. This gives realistic frame
    # lengths and repeatable UI/network load while retaining a valid CRC.
    state = (
        (message_type * 1103515245)
        ^ (station_id * 12345)
        ^ (sequence * 2654435761)
    ) & 0xFFFFFFFF

    for index in range(3, payload_size):
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        payload[index] = (state >> 24) & 0xFF

    return build_rtcm_frame(bytes(payload))


def validate_rtcm_frame(frame: bytes) -> bool:
    """Validate RTCM preamble, declared length and CRC."""
    if len(frame) < 6 or frame[0] != 0xD3:
        return False

    if frame[1] & 0xFC:
        return False

    payload_length = ((frame[1] & 0x03) << 8) | frame[2]
    expected_length = 3 + payload_length + 3

    if len(frame) != expected_length:
        return False

    expected_crc = int.from_bytes(frame[-3:], "big")
    return crc24q(frame[:-3]) == expected_crc


def load_rtcm_file(path: Path) -> list[bytes]:
    """Extract all CRC-valid RTCM3 frames from a binary capture."""
    data = path.read_bytes()
    frames: list[bytes] = []
    offset = 0

    while offset < len(data):
        start = data.find(b"\xD3", offset)

        if start < 0:
            break

        if start + 3 > len(data):
            break

        if data[start + 1] & 0xFC:
            offset = start + 1
            continue

        payload_length = ((data[start + 1] & 0x03) << 8) | data[start + 2]
        frame_length = 3 + payload_length + 3
        end = start + frame_length

        if end > len(data):
            break

        frame = data[start:end]

        if validate_rtcm_frame(frame):
            frames.append(frame)
            offset = end
        else:
            offset = start + 1

    if not frames:
        raise ValueError(f"No valid RTCM3 frame found in {path}.")

    return frames


@dataclass(frozen=True)
class StationConfig:
    device_id: str
    token: str
    mountpoint: str
    network_type: str
    ip: str
    latitude: float
    longitude: float
    altitude_m: float
    station_id: int


@dataclass
class StationRuntime:
    config: StationConfig
    started_at: float = field(default_factory=time.monotonic)
    connected: bool = False
    reconnect_count: int = 0
    bytes_sent: int = 0
    frames_valid: int = 0
    crc_errors: int = 0
    queue_drops: int = 0
    stale_drops: int = 0
    last_frame_at: float | None = None
    message_counts: Counter[int] = field(default_factory=Counter)
    minimum_free_heap_bytes: int = 174_000
    _last_rate_time: float = field(default_factory=time.monotonic)
    _last_rate_bytes: int = 0
    _upload_bps: int = 0
    _lock: threading.Lock = field(default_factory=threading.Lock)

    def set_connected(self, connected: bool) -> None:
        with self._lock:
            self.connected = connected

    def record_reconnect(self) -> None:
        with self._lock:
            self.reconnect_count += 1

    def record_frame(self, frame: bytes) -> None:
        message_type = rtcm_message_type(frame)

        with self._lock:
            self.bytes_sent += len(frame)
            self.frames_valid += 1
            self.message_counts[message_type] += 1
            self.last_frame_at = time.monotonic()

    def snapshot(
        self,
        caster_host: str,
        caster_port: int,
        management_url: str,
    ) -> dict[str, Any]:
        now = time.monotonic()

        with self._lock:
            elapsed = max(0.001, now - self._last_rate_time)
            bytes_delta = self.bytes_sent - self._last_rate_bytes
            self._upload_bps = round(bytes_delta * 8 / elapsed)
            self._last_rate_time = now
            self._last_rate_bytes = self.bytes_sent

            uptime_s = max(1, int(now - self.started_at))
            phase = uptime_s * 0.035 + self.config.station_id

            free_heap_bytes = int(
                184_000 + 4_000 * math.sin(phase)
            )
            self.minimum_free_heap_bytes = min(
                self.minimum_free_heap_bytes,
                free_heap_bytes,
            )

            temperature_c = round(
                44.0 + 1.8 * math.sin(phase * 0.45),
                1,
            )

            rssi = None
            link_speed_mbps = 100

            if self.config.network_type == "wifi":
                rssi = int(-53 + 5 * math.sin(phase * 0.6))
                link_speed_mbps = 72

            age_ms = None

            if self.last_frame_at is not None:
                age_ms = max(0, round((now - self.last_frame_at) * 1000))

            survey_duration_s = 900 + uptime_s
            mean_accuracy_m = round(
                0.0125 + 0.0015 * abs(math.sin(phase * 0.2)),
                4,
            )

            return {
                "firmware_version": FIRMWARE_VERSION,
                "source_connected": self.connected,
                "network": {
                    "connected": True,
                    "type": self.config.network_type,
                    "ip": self.config.ip,
                    "rssi": rssi,
                    "link_speed_mbps": link_speed_mbps,
                    "management_url": management_url,
                },
                "survey_in": {
                    "active": False,
                    "valid": True,
                    "duration_s": survey_duration_s,
                    "mean_accuracy_m": mean_accuracy_m,
                    "observations": 1800 + uptime_s,
                    "latitude": self.config.latitude,
                    "longitude": self.config.longitude,
                    "altitude_m": self.config.altitude_m,
                },
                "rtcm": {
                    "format": RTCM_FORMAT,
                    "receiver": "u-blox ZED-F9P",
                    "uart_baud": 115200,
                    "caster_host": caster_host,
                    "caster_port": caster_port,
                    "mountpoint": self.config.mountpoint,
                    "connected": self.connected,
                    "reconnect_count": self.reconnect_count,
                    "bytes_sent": self.bytes_sent,
                    "frames_valid": self.frames_valid,
                    "crc_errors": self.crc_errors,
                    "queue_drops": self.queue_drops,
                    "stale_drops": self.stale_drops,
                    "age_ms": age_ms,
                    "upload_bps": self._upload_bps,
                    "message_counts": {
                        str(key): value
                        for key, value in sorted(self.message_counts.items())
                    },
                },
                "system": {
                    "uptime_s": uptime_s,
                    "free_heap_bytes": free_heap_bytes,
                    "minimum_free_heap_bytes": self.minimum_free_heap_bytes,
                    "temperature_c": temperature_c,
                    "cpu_frequency_mhz": 240,
                    "sdk_version": "ESP-IDF v6.0.2",
                    "reset_reason": "POWERON_RESET",
                },
            }



@dataclass(frozen=True)
class RoverConfig:
    """One simulated Raspberry Pi NTRIP bridge instance."""

    name: str

    ntrip_host: str
    ntrip_port: int
    mountpoint: str
    username: str = ""
    password: str = ""
    use_tls: bool = False

    fixed_latitude: float | None = None
    fixed_longitude: float | None = None
    fixed_altitude_m: float = 0.0

    rtcm_whitelist: frozenset[int] = frozenset()
    user_agent: str = "NTRIP PiNtripBridge/1.0"

    mavlink_output: str = "none"  # none, udp or serial
    mavlink_udp_host: str = "127.0.0.1"
    mavlink_udp_port: int = 14550
    mavlink_serial_device: str = "/dev/serial0"
    mavlink_serial_baud: int = 921600
    mavlink_sysid: int = 255
    mavlink_compid: int = 190


@dataclass
class RoverRuntime:
    config: RoverConfig
    started_at: float = field(default_factory=time.monotonic)
    connected: bool = False
    connection_status: str = "disconnected"
    last_error: str | None = None
    reconnect_count: int = 0
    bytes_received: int = 0
    frames_valid: int = 0
    crc_errors: int = 0
    frames_forwarded: int = 0
    whitelist_drops: int = 0
    gga_sent: int = 0
    mavlink_packets_sent: int = 0
    mavlink_bytes_sent: int = 0
    mavlink_write_errors: int = 0
    last_frame_at: float | None = None
    message_counts: Counter[int] = field(default_factory=Counter)
    _last_rate_time: float = field(default_factory=time.monotonic)
    _last_rate_bytes: int = 0
    _download_bps: int = 0
    _lock: threading.Lock = field(default_factory=threading.Lock)

    def set_status(
        self,
        status: str,
        *,
        connected: bool | None = None,
        error: str | None = None,
    ) -> None:
        with self._lock:
            self.connection_status = status
            if connected is not None:
                self.connected = connected
            self.last_error = error

    def record_reconnect(self) -> None:
        with self._lock:
            self.reconnect_count += 1

    def record_bytes(self, byte_count: int) -> None:
        with self._lock:
            self.bytes_received += max(0, byte_count)

    def record_frame(self, frame: bytes, forwarded: bool) -> None:
        message_type = rtcm_message_type(frame)

        with self._lock:
            self.frames_valid += 1
            self.message_counts[message_type] += 1
            self.last_frame_at = time.monotonic()
            if forwarded:
                self.frames_forwarded += 1
            else:
                self.whitelist_drops += 1

    def record_crc_errors(self, count: int) -> None:
        if count <= 0:
            return

        with self._lock:
            self.crc_errors += count

    def record_gga(self) -> None:
        with self._lock:
            self.gga_sent += 1

    def record_mavlink(self, packet_length: int, write_ok: bool) -> None:
        with self._lock:
            if write_ok:
                self.mavlink_packets_sent += 1
                self.mavlink_bytes_sent += max(0, packet_length)
            else:
                self.mavlink_write_errors += 1

    def snapshot(self) -> dict[str, Any]:
        now = time.monotonic()

        with self._lock:
            elapsed = max(0.001, now - self._last_rate_time)
            bytes_delta = self.bytes_received - self._last_rate_bytes
            self._download_bps = round(bytes_delta * 8 / elapsed)
            self._last_rate_time = now
            self._last_rate_bytes = self.bytes_received

            age_ms = None
            if self.last_frame_at is not None:
                age_ms = max(0, round((now - self.last_frame_at) * 1000))

            return {
                "name": self.config.name,
                "host": self.config.ntrip_host,
                "port": self.config.ntrip_port,
                "mountpoint": self.config.mountpoint,
                "connected": self.connected,
                "status": self.connection_status,
                "last_error": self.last_error,
                "reconnect_count": self.reconnect_count,
                "download_bps": self._download_bps,
                "bytes_received": self.bytes_received,
                "frames_valid": self.frames_valid,
                "crc_errors": self.crc_errors,
                "frames_forwarded": self.frames_forwarded,
                "whitelist_drops": self.whitelist_drops,
                "gga_sent": self.gga_sent,
                "mavlink_packets_sent": self.mavlink_packets_sent,
                "mavlink_bytes_sent": self.mavlink_bytes_sent,
                "mavlink_write_errors": self.mavlink_write_errors,
                "age_ms": age_ms,
                "message_counts": {
                    str(key): value
                    for key, value in sorted(self.message_counts.items())
                },
            }


class RtcmReceiveParser:
    """Incrementally extract and CRC-check RTCM3 frames from TCP."""

    def __init__(self) -> None:
        self.buffer = bytearray()

    def reset(self) -> None:
        self.buffer.clear()

    def feed(self, data: bytes) -> tuple[list[bytes], int]:
        self.buffer.extend(data)
        frames: list[bytes] = []
        crc_errors = 0

        while True:
            if len(self.buffer) < 3:
                break

            if self.buffer[0] != 0xD3:
                try:
                    preamble_index = self.buffer.index(0xD3)
                    del self.buffer[:preamble_index]
                except ValueError:
                    self.buffer.clear()
                    break

            if len(self.buffer) < 3:
                break

            if self.buffer[1] & 0xFC:
                del self.buffer[0]
                continue

            payload_length = ((self.buffer[1] & 0x03) << 8) | self.buffer[2]
            frame_length = 3 + payload_length + 3

            if len(self.buffer) < frame_length:
                break

            frame = bytes(self.buffer[:frame_length])

            if validate_rtcm_frame(frame):
                frames.append(frame)
                del self.buffer[:frame_length]
                continue

            crc_errors += 1
            # Match the hardware parser's resynchronisation strategy: discard
            # the bad preamble and scan for the next D3 byte.
            del self.buffer[0]

        return frames, crc_errors


def _nmea_coordinate(value: float, latitude: bool) -> tuple[str, str]:
    absolute = abs(value)
    degrees = int(absolute)
    minutes = (absolute - degrees) * 60.0

    # ntrip.cc rounds to exactly four decimal places and handles minute carry.
    rounded_minutes = round(minutes, 4)
    if rounded_minutes >= 60.0:
        rounded_minutes -= 60.0
        degrees += 1

    if latitude:
        coordinate = f"{degrees:02d}{rounded_minutes:07.4f}"
        hemisphere = "N" if value >= 0 else "S"
    else:
        coordinate = f"{degrees:03d}{rounded_minutes:07.4f}"
        hemisphere = "E" if value >= 0 else "W"

    return coordinate, hemisphere


def build_pi_bridge_gga(
    latitude: float,
    longitude: float,
    altitude_m: float,
    *,
    utc_time: time.struct_time | None = None,
) -> bytes:
    """Build the exact GGA shape generated by NTRIPBridge::makeGGA()."""
    utc = utc_time or time.gmtime()
    timestamp = f"{utc.tm_hour:02d}{utc.tm_min:02d}{utc.tm_sec:02d}"
    latitude_text, latitude_hemisphere = _nmea_coordinate(
        latitude, latitude=True
    )
    longitude_text, longitude_hemisphere = _nmea_coordinate(
        longitude, latitude=False
    )

    core = (
        f"GPGGA,{timestamp},"
        f"{latitude_text},{latitude_hemisphere},"
        f"{longitude_text},{longitude_hemisphere},"
        f"1,12,1.0,{altitude_m:.1f},M,0.0,M,,"
    )

    checksum = 0
    for byte in core.encode("ascii"):
        checksum ^= byte

    return f"${core}*{checksum:02X}\r\n".encode("ascii")


def build_pi_bridge_handshake(config: RoverConfig) -> bytes:
    """Build the exact HTTP request emitted by NTRIPClient::sendHttpHandshake."""
    request = (
        f"GET /{config.mountpoint} HTTP/1.0\r\n"
        f"Host: {config.ntrip_host}\r\n"
        "Ntrip-Version: Ntrip/2.0\r\n"
        f"User-Agent: {config.user_agent}\r\n"
    )

    if config.username or config.password:
        encoded = base64.b64encode(
            f"{config.username}:{config.password}".encode("utf-8")
        ).decode("ascii")
        request += f"Authorization: Basic {encoded}\r\n"

    return (request + "\r\n").encode("ascii")


def parse_rtcm_whitelist(value: str) -> frozenset[int]:
    ids: set[int] = set()
    for raw in value.split(","):
        token = raw.strip()
        if not token:
            continue
        message_id = int(token)
        if not 0 <= message_id <= 4095:
            raise ValueError(f"Invalid RTCM message ID: {message_id}")
        ids.add(message_id)
    return frozenset(ids)


def load_key_value_config(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"Malformed config line {line_number}: {line}")
        key, value = (part.strip() for part in line.split("=", 1))
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key] = value
    return values


def _config_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _optional_float(values: dict[str, str], key: str) -> float | None:
    value = values.get(key)
    if value is None or value.strip() == "":
        return None
    return float(value)


def load_pi_bridge_config(
    path: Path,
    *,
    name: str,
    mavlink_output_override: str,
    udp_host_override: str,
    udp_port_override: int,
    serial_device_override: str,
    serial_baud_override: int,
    sysid_override: int,
    compid_override: int,
) -> RoverConfig:
    values = load_key_value_config(path)

    ntrip_host = values.get("ntrip_host", "").strip()
    mountpoint = values.get("ntrip_mountpoint", "").strip()
    if not ntrip_host:
        raise ValueError("ntrip_host is required in the client config.")
    if not mountpoint:
        raise ValueError("ntrip_mountpoint is required in the client config.")

    use_tls = _config_bool(values.get("ntrip_use_tls"), False)
    if use_tls:
        raise ValueError(
            "ntrip_use_tls=true is not supported by the current C++ client, "
            "so the hardware-faithful simulator rejects it too."
        )

    configured_mavlink_type = values.get("mavlink_type", "serial").strip()
    if mavlink_output_override == "config":
        mavlink_output = configured_mavlink_type
    else:
        mavlink_output = mavlink_output_override

    return RoverConfig(
        name=name,
        ntrip_host=ntrip_host,
        ntrip_port=int(values.get("ntrip_port", "2101")),
        mountpoint=mountpoint,
        username=values.get("ntrip_user", ""),
        password=values.get("ntrip_password", ""),
        use_tls=use_tls,
        fixed_latitude=_optional_float(values, "fixed_lat"),
        fixed_longitude=_optional_float(values, "fixed_lon"),
        fixed_altitude_m=float(values.get("fixed_alt", "0") or 0),
        rtcm_whitelist=parse_rtcm_whitelist(values.get("rtcm_whitelist", "")),
        mavlink_output=mavlink_output,
        mavlink_udp_host=(
            values.get("mavlink_udp_host", "127.0.0.1")
            if mavlink_output_override == "config"
            else udp_host_override
        ),
        mavlink_udp_port=(
            int(values.get("mavlink_udp_port", "14550"))
            if mavlink_output_override == "config"
            else udp_port_override
        ),
        mavlink_serial_device=(
            values.get("mavlink_serial_device", "/dev/serial0")
            if mavlink_output_override == "config"
            else serial_device_override
        ),
        mavlink_serial_baud=(
            int(values.get("mavlink_serial_baud", "921600"))
            if mavlink_output_override == "config"
            else serial_baud_override
        ),
        mavlink_sysid=(
            int(values.get("mavlink_sysid", "255"))
            if mavlink_output_override == "config"
            else sysid_override
        ),
        mavlink_compid=(
            int(values.get("mavlink_compid", "190"))
            if mavlink_output_override == "config"
            else compid_override
        ),
    )


# MAVLink 2 GPS_RTCM_DATA constants from common.xml/generated C headers.
MAVLINK2_MAGIC = 0xFD
MAVLINK_MSG_ID_GPS_RTCM_DATA = 233
MAVLINK_GPS_RTCM_DATA_PAYLOAD_LEN = 182
MAVLINK_GPS_RTCM_DATA_MAX_FIELD = 180
MAVLINK_GPS_RTCM_DATA_MAX_LOGICAL = 720
MAVLINK_GPS_RTCM_DATA_CRC_EXTRA = 35
MAVLINK_MSG_ID_GLOBAL_POSITION_INT = 33
MAVLINK_GLOBAL_POSITION_INT_PAYLOAD_LEN = 28
MAVLINK_GLOBAL_POSITION_INT_CRC_EXTRA = 104


def mavlink_x25_crc(data: bytes, crc_extra: int) -> int:
    crc = 0xFFFF

    def accumulate(byte: int, current: int) -> int:
        temporary = byte ^ (current & 0xFF)
        temporary ^= (temporary << 4) & 0xFF
        return (
            (current >> 8)
            ^ (temporary << 8)
            ^ (temporary << 3)
            ^ (temporary >> 4)
        ) & 0xFFFF

    for byte in data:
        crc = accumulate(byte, crc)
    return accumulate(crc_extra, crc)


def build_mavlink2_packet(
    *,
    payload: bytes,
    message_id: int,
    packet_sequence: int,
    system_id: int,
    component_id: int,
    crc_extra: int,
) -> bytes:
    if len(payload) > 255:
        raise ValueError("MAVLink payload exceeds 255 bytes.")

    header_without_magic = bytes(
        (
            len(payload),
            0,  # incompat flags
            0,  # compat flags
            packet_sequence & 0xFF,
            system_id & 0xFF,
            component_id & 0xFF,
        )
    ) + int(message_id).to_bytes(3, "little")

    checksum = mavlink_x25_crc(
        header_without_magic + payload,
        crc_extra,
    )

    return (
        bytes((MAVLINK2_MAGIC,))
        + header_without_magic
        + payload
        + checksum.to_bytes(2, "little")
    )


def validate_mavlink2_packet(packet: bytes, crc_extra: int) -> bool:
    if len(packet) < 12 or packet[0] != MAVLINK2_MAGIC:
        return False
    payload_length = packet[1]
    signature_length = 13 if packet[2] & 0x01 else 0
    expected_length = 10 + payload_length + 2 + signature_length
    if len(packet) != expected_length:
        return False
    checksum_end = len(packet) - signature_length
    received = int.from_bytes(packet[checksum_end - 2 : checksum_end], "little")
    computed = mavlink_x25_crc(packet[1 : 10 + payload_length], crc_extra)
    return received == computed


class MavlinkStreamParser:
    """Small MAVLink v1/v2 stream parser for GLOBAL_POSITION_INT."""

    def __init__(self) -> None:
        self.buffer = bytearray()

    def feed(self, data: bytes) -> list[bytes]:
        self.buffer.extend(data)
        packets: list[bytes] = []

        while self.buffer:
            try:
                v2_index = self.buffer.index(0xFD)
            except ValueError:
                v2_index = len(self.buffer)
            try:
                v1_index = self.buffer.index(0xFE)
            except ValueError:
                v1_index = len(self.buffer)

            start = min(v1_index, v2_index)
            if start == len(self.buffer):
                self.buffer.clear()
                break
            if start > 0:
                del self.buffer[:start]
            if len(self.buffer) < 2:
                break

            magic = self.buffer[0]
            payload_length = self.buffer[1]
            if magic == 0xFD:
                if len(self.buffer) < 10:
                    break
                signature_length = 13 if self.buffer[2] & 0x01 else 0
                packet_length = 10 + payload_length + 2 + signature_length
            else:
                if len(self.buffer) < 6:
                    break
                packet_length = 6 + payload_length + 2

            if len(self.buffer) < packet_length:
                break
            packets.append(bytes(self.buffer[:packet_length]))
            del self.buffer[:packet_length]

        return packets


def decode_global_position_int(packet: bytes) -> tuple[float, float, float] | None:
    if not packet:
        return None

    if packet[0] == 0xFD:
        payload_length = packet[1]
        message_id = int.from_bytes(packet[7:10], "little")
        payload_offset = 10
        signature_length = 13 if packet[2] & 0x01 else 0
        checksum_end = len(packet) - signature_length
        if message_id != MAVLINK_MSG_ID_GLOBAL_POSITION_INT:
            return None
        if payload_length < MAVLINK_GLOBAL_POSITION_INT_PAYLOAD_LEN:
            return None
        received = int.from_bytes(packet[checksum_end - 2 : checksum_end], "little")
        computed = mavlink_x25_crc(
            packet[1 : payload_offset + payload_length],
            MAVLINK_GLOBAL_POSITION_INT_CRC_EXTRA,
        )
        if received != computed:
            return None
    elif packet[0] == 0xFE:
        payload_length = packet[1]
        message_id = packet[5]
        payload_offset = 6
        if message_id != MAVLINK_MSG_ID_GLOBAL_POSITION_INT:
            return None
        if payload_length < MAVLINK_GLOBAL_POSITION_INT_PAYLOAD_LEN:
            return None
        received = int.from_bytes(packet[-2:], "little")
        computed = mavlink_x25_crc(
            packet[1 : payload_offset + payload_length],
            MAVLINK_GLOBAL_POSITION_INT_CRC_EXTRA,
        )
        if received != computed:
            return None
    else:
        return None

    payload = packet[payload_offset : payload_offset + payload_length]
    _, latitude_e7, longitude_e7, altitude_mm, _, _, _, _, _ = struct.unpack_from(
        "<IiiiihhhH", payload, 0
    )
    latitude = latitude_e7 * 1e-7
    longitude = longitude_e7 * 1e-7
    altitude_m = altitude_mm * 1e-3

    if not math.isfinite(latitude) or not math.isfinite(longitude):
        return None
    if latitude == 0.0 and longitude == 0.0:
        return None
    if abs(latitude) > 90.0 or abs(longitude) > 180.0:
        return None
    return latitude, longitude, altitude_m if math.isfinite(altitude_m) else 0.0


class MavlinkGpsRtcmOutput:
    """Optional hardware-compatible GPS_RTCM_DATA output."""

    def __init__(self, config: RoverConfig, runtime: RoverRuntime) -> None:
        self.config = config
        self.runtime = runtime
        self._udp_socket: socket.socket | None = None
        self._serial_fd: int | None = None
        self._packet_sequence = 0
        self._rtcm_sequence = 0
        self._rx_parser = MavlinkStreamParser()
        self._lock = threading.Lock()

    def start(self) -> None:
        mode = self.config.mavlink_output
        if mode == "none":
            return
        if mode == "udp":
            udp = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            udp.connect((self.config.mavlink_udp_host, self.config.mavlink_udp_port))
            udp.setblocking(False)
            self._udp_socket = udp
            return
        if mode == "serial":
            self._serial_fd = self._open_serial(
                self.config.mavlink_serial_device,
                self.config.mavlink_serial_baud,
            )
            return
        raise ValueError(f"Unsupported MAVLink output mode: {mode}")

    def close(self) -> None:
        if self._udp_socket is not None:
            self._udp_socket.close()
            self._udp_socket = None
        if self._serial_fd is not None:
            os.close(self._serial_fd)
            self._serial_fd = None

    def _open_serial(self, device: str, baud: int) -> int:
        baud_constants = {
            9600: termios.B9600,
            19200: termios.B19200,
            38400: termios.B38400,
            57600: termios.B57600,
            115200: termios.B115200,
            230400: getattr(termios, "B230400", None),
            460800: getattr(termios, "B460800", None),
            500000: getattr(termios, "B500000", None),
            576000: getattr(termios, "B576000", None),
            921600: getattr(termios, "B921600", None),
            1000000: getattr(termios, "B1000000", None),
            1152000: getattr(termios, "B1152000", None),
            1500000: getattr(termios, "B1500000", None),
            2000000: getattr(termios, "B2000000", None),
        }
        speed = baud_constants.get(baud)
        if speed is None:
            raise ValueError(f"Unsupported serial baud: {baud}")

        fd = os.open(device, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
        attrs = termios.tcgetattr(fd)
        attrs[0] = 0
        attrs[1] = 0
        attrs[2] = termios.CS8 | termios.CREAD | termios.CLOCAL
        attrs[3] = 0
        attrs[4] = speed
        attrs[5] = speed
        termios.tcsetattr(fd, termios.TCSANOW, attrs)
        return fd

    def _write(self, packet: bytes) -> bool:
        try:
            if self._udp_socket is not None:
                self._udp_socket.send(packet)
                return True
            if self._serial_fd is not None:
                view = memoryview(packet)
                while view:
                    try:
                        written = os.write(self._serial_fd, view)
                    except BlockingIOError:
                        time.sleep(0.01)
                        continue
                    view = view[written:]
                return True
            return self.config.mavlink_output == "none"
        except OSError:
            return False

    def poll_position(self) -> tuple[float, float, float] | None:
        """Read the latest PX4 GLOBAL_POSITION_INT from the MAVLink link."""
        chunks: list[bytes] = []

        if self._udp_socket is not None:
            while True:
                try:
                    chunks.append(self._udp_socket.recv(4096))
                except BlockingIOError:
                    break
                except OSError:
                    break

        if self._serial_fd is not None:
            while True:
                try:
                    chunk = os.read(self._serial_fd, 4096)
                except BlockingIOError:
                    break
                except OSError:
                    break
                if not chunk:
                    break
                chunks.append(chunk)

        latest: tuple[float, float, float] | None = None
        for chunk in chunks:
            for packet in self._rx_parser.feed(chunk):
                position = decode_global_position_int(packet)
                if position is not None:
                    latest = position
        return latest

    def send_rtcm(self, frame: bytes) -> None:
        data = frame[:MAVLINK_GPS_RTCM_DATA_MAX_LOGICAL]
        with self._lock:
            logical_sequence = self._rtcm_sequence & 0x1F
            self._rtcm_sequence = (self._rtcm_sequence + 1) & 0xFF

            chunks: list[tuple[int, bytes]] = []
            if len(data) < MAVLINK_GPS_RTCM_DATA_MAX_FIELD:
                chunks.append(((logical_sequence & 0x1F) << 3, data))
            else:
                for fragment_id, offset in enumerate(
                    range(0, len(data), MAVLINK_GPS_RTCM_DATA_MAX_FIELD)
                ):
                    flags = (
                        0x01
                        | ((fragment_id & 0x03) << 1)
                        | ((logical_sequence & 0x1F) << 3)
                    )
                    chunks.append(
                        (flags, data[offset : offset + MAVLINK_GPS_RTCM_DATA_MAX_FIELD])
                    )

            for flags, chunk in chunks:
                payload = (
                    bytes((flags, len(chunk)))
                    + chunk
                    + bytes(MAVLINK_GPS_RTCM_DATA_MAX_FIELD - len(chunk))
                )
                packet = build_mavlink2_packet(
                    payload=payload,
                    message_id=MAVLINK_MSG_ID_GPS_RTCM_DATA,
                    packet_sequence=self._packet_sequence,
                    system_id=self.config.mavlink_sysid,
                    component_id=self.config.mavlink_compid,
                    crc_extra=MAVLINK_GPS_RTCM_DATA_CRC_EXTRA,
                )
                self._packet_sequence = (self._packet_sequence + 1) & 0xFF
                write_ok = self._write(packet)
                self.runtime.record_mavlink(len(packet), write_ok)


class NtripRoverWorker(threading.Thread):
    """Emulate the deployed Raspberry Pi NTRIP -> MAVLink bridge."""

    def __init__(
        self,
        runtime: RoverRuntime,
        timeout_s: float,
        stop_event: threading.Event,
        start_delay_s: float,
        gga_interval_s: float,
        debug: bool,
    ) -> None:
        super().__init__(name=f"ROVER-{runtime.config.name}", daemon=True)
        self.runtime = runtime
        self.timeout_s = timeout_s
        self.stop_event = stop_event
        self.start_delay_s = start_delay_s
        self.gga_interval_s = gga_interval_s
        self.debug = debug
        self._stream_was_connected = False
        self._next_gga_at = time.monotonic()
        self._mavlink = MavlinkGpsRtcmOutput(runtime.config, runtime)
        self._vehicle_position: tuple[float, float, float] | None = None

    def run(self) -> None:
        if self.stop_event.wait(self.start_delay_s):
            return

        try:
            self._mavlink.start()
        except (OSError, ValueError) as error:
            self.runtime.set_status("error", connected=False, error=str(error))
            print(f"[{self.runtime.config.name}] MAVLINK ERROR: {error}", file=sys.stderr)
            return

        attempts = 0
        try:
            while not self.stop_event.is_set():
                self._stream_was_connected = False
                try:
                    self.runtime.set_status("connecting", connected=False)
                    self._run_connection()
                except (ConnectionError, OSError, TimeoutError) as error:
                    self.runtime.set_status("error", connected=False, error=str(error))
                    self.runtime.record_reconnect()
                    print(
                        f"[{self.runtime.config.name}] ROVER ERROR: {error}",
                        file=sys.stderr,
                    )

                if self.stop_event.is_set():
                    break

                if self._stream_was_connected:
                    attempts = 0

                backoff_s = min(16, 1 << min(attempts, 4))
                attempts += 1
                self.runtime.set_status("reconnecting", connected=False)
                if self.debug:
                    print(
                        f"[{self.runtime.config.name}] reconnect in {backoff_s}s "
                        f"(attempt {attempts})"
                    )
                self.stop_event.wait(backoff_s)
        finally:
            self.runtime.set_status("disconnected", connected=False)
            self._mavlink.close()

    def _run_connection(self) -> None:
        config = self.runtime.config
        if config.use_tls:
            raise ConnectionError("TLS is not implemented by the deployed C++ client.")

        with socket.create_connection(
            (config.ntrip_host, config.ntrip_port), timeout=self.timeout_s
        ) as stream:
            stream.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
            stream.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
            stream.settimeout(self.timeout_s)

            request = build_pi_bridge_handshake(config)
            if self.debug:
                printable = request.decode("ascii").replace(
                    f"Authorization: Basic {base64.b64encode(f'{config.username}:{config.password}'.encode()).decode()}",
                    "Authorization: Basic <redacted>",
                )
                print(f"[{config.name}] TX handshake:\n{printable.rstrip()}")
            stream.sendall(request)

            remaining = self._read_http_response(stream)
            parser = RtcmReceiveParser()
            self.runtime.set_status("connected", connected=True)
            self._stream_was_connected = True

            if remaining:
                self._consume_rtcm(parser, remaining)

            stream.settimeout(0.5)
            while not self.stop_event.is_set():
                now = time.monotonic()
                mavlink_position = self._mavlink.poll_position()
                if mavlink_position is not None:
                    self._vehicle_position = mavlink_position
                if now >= self._next_gga_at:
                    self._send_gga_if_available(stream)
                    while self._next_gga_at <= now:
                        self._next_gga_at += self.gga_interval_s

                try:
                    data = stream.recv(4096)
                except socket.timeout:
                    continue

                if not data:
                    raise ConnectionError("server closed the RTCM stream")
                self._consume_rtcm(parser, data)

    def _read_http_response(self, stream: socket.socket) -> bytes:
        response = bytearray()
        deadline = time.monotonic() + 10.0

        while not self.stop_event.is_set():
            if time.monotonic() > deadline:
                raise TimeoutError("HTTP response timeout")
            try:
                chunk = stream.recv(512)
            except socket.timeout:
                continue
            if not chunk:
                raise ConnectionError("peer closed during HTTP handshake")
            response.extend(chunk)
            if len(response) > 16 * 1024:
                raise ConnectionError("HTTP response header too large")

            separator_index = response.find(b"\r\n\r\n")
            if separator_index < 0:
                continue

            header = bytes(response[:separator_index])
            remaining = bytes(response[separator_index + 4 :])
            status_line = header.split(b"\r\n", 1)[0].decode(
                "ascii", errors="replace"
            )
            parts = status_line.split()
            try:
                code = int(parts[1])
            except (IndexError, ValueError) as error:
                raise ConnectionError(f"invalid HTTP response: {status_line}") from error

            if 200 <= code < 300:
                if self.debug:
                    print(
                        f"[{self.runtime.config.name}] RX {status_line}; "
                        f"trailing={len(remaining)} bytes"
                    )
                return remaining
            if code == 401:
                raise ConnectionError("HTTP 401 unauthorized (check user/password)")
            if code == 404:
                raise ConnectionError("HTTP 404 not found (check mountpoint)")
            if code == 429:
                raise ConnectionError("HTTP 429 connection limit reached")
            raise ConnectionError(f"HTTP {code}: {status_line}")

        raise ConnectionError("stopped during HTTP handshake")

    def _send_gga_if_available(self, stream: socket.socket) -> None:
        config = self.runtime.config
        position = self._vehicle_position
        if position is None:
            if config.fixed_latitude is None or config.fixed_longitude is None:
                return
            position = (
                config.fixed_latitude,
                config.fixed_longitude,
                config.fixed_altitude_m,
            )
        sentence = build_pi_bridge_gga(*position)
        stream.sendall(sentence)
        self.runtime.record_gga()
        if self.debug:
            print(f"[{config.name}] GGA {sentence.decode('ascii').strip()}")

    def _consume_rtcm(self, parser: RtcmReceiveParser, data: bytes) -> None:
        self.runtime.record_bytes(len(data))
        frames, crc_errors = parser.feed(data)
        self.runtime.record_crc_errors(crc_errors)

        whitelist = self.runtime.config.rtcm_whitelist
        for frame in frames:
            message_id = rtcm_message_type(frame)
            forwarded = not whitelist or message_id in whitelist
            self.runtime.record_frame(frame, forwarded)
            if forwarded:
                self._mavlink.send_rtcm(frame)
            elif self.debug:
                print(
                    f"[{self.runtime.config.name}] drop RTCM {message_id} "
                    "(not in whitelist)"
                )


class NtripSourceWorker(threading.Thread):
    """Maintain one NTRIP source connection and stream RTCM frames."""

    def __init__(
        self,
        runtime: StationRuntime,
        caster_host: str,
        caster_port: int,
        timeout_s: float,
        stop_event: threading.Event,
        real_frames: list[bytes] | None,
        replay_delay_s: float,
    ) -> None:
        super().__init__(
            name=f"NTRIP-{runtime.config.device_id}",
            daemon=True,
        )
        self.runtime = runtime
        self.caster_host = caster_host
        self.caster_port = caster_port
        self.timeout_s = timeout_s
        self.stop_event = stop_event
        self.real_frames = real_frames
        self.replay_delay_s = replay_delay_s
        self._sequence = 0

    def run(self) -> None:
        while not self.stop_event.is_set():
            try:
                self._run_connection()
            except (ConnectionError, OSError, TimeoutError) as error:
                self.runtime.set_connected(False)
                self.runtime.record_reconnect()
                print(
                    f"[{self.runtime.config.device_id}] "
                    f"NTRIP ERROR: {error}",
                    file=sys.stderr,
                )
                self.stop_event.wait(1.0)

        self.runtime.set_connected(False)

    def _run_connection(self) -> None:
        config = self.runtime.config

        with socket.create_connection(
            (self.caster_host, self.caster_port),
            timeout=self.timeout_s,
        ) as stream:
            stream.settimeout(self.timeout_s)
            mountpoint = quote(config.mountpoint, safe="-_.~")

            request = (
                f"POST /{mountpoint} HTTP/1.1\r\n"
                f"Host: {self.caster_host}:{self.caster_port}\r\n"
                "User-Agent: ESP32-NTRIP-Simulator/2.1\r\n"
                "Ntrip-Version: Ntrip/2.0\r\n"
                f"Authorization: Bearer {config.token}\r\n"
                "Content-Type: gnss/data\r\n"
                "Connection: keep-alive\r\n"
                "\r\n"
            ).encode("ascii")

            stream.sendall(request)
            response = self._read_headers(stream)
            status_line = response.splitlines()[0].decode(
                "ascii",
                errors="replace",
            )

            if "200" not in status_line:
                raise ConnectionError(
                    f"{config.device_id}: NTRIP source rejected: {status_line}"
                )

            stream.settimeout(None)
            self.runtime.set_connected(True)

            if self.real_frames:
                self._stream_real_frames(stream)
            else:
                self._stream_synthetic_frames(stream)

    def _read_headers(self, stream: socket.socket) -> bytes:
        response = bytearray()

        while len(response) < 8192:
            chunk = stream.recv(1024)

            if not chunk:
                raise ConnectionError("Caster closed during handshake.")

            response.extend(chunk)

            if b"\r\n\r\n" in response or b"\n\n" in response:
                return bytes(response)

        raise ConnectionError("Caster response headers are too large.")

    def _stream_real_frames(self, stream: socket.socket) -> None:
        assert self.real_frames is not None
        index = 0

        while not self.stop_event.is_set():
            frame = self.real_frames[index]
            stream.sendall(frame)
            self.runtime.record_frame(frame)

            index = (index + 1) % len(self.real_frames)
            self.stop_event.wait(self.replay_delay_s)

    def _stream_synthetic_frames(self, stream: socket.socket) -> None:
        config = self.runtime.config
        now = time.monotonic()
        next_due = {
            message_type: now
            for message_type in RTCM_PERIODS_S
        }

        while not self.stop_event.is_set():
            now = time.monotonic()
            sent_any = False

            for message_type, period_s in RTCM_PERIODS_S.items():
                if now < next_due[message_type]:
                    continue

                if message_type == 1005:
                    frame = build_type_1005(
                        station_id=config.station_id,
                        latitude=config.latitude,
                        longitude=config.longitude,
                        altitude_m=config.altitude_m,
                    )
                else:
                    frame = build_synthetic_rtcm_frame(
                        message_type=message_type,
                        station_id=config.station_id,
                        sequence=self._sequence,
                    )

                stream.sendall(frame)
                self.runtime.record_frame(frame)

                self._sequence += 1
                next_due[message_type] += period_s

                while next_due[message_type] <= now:
                    next_due[message_type] += period_s

                sent_any = True

            self.stop_event.wait(0.01 if sent_any else 0.03)


class TelemetrySender:
    def __init__(
        self,
        base_url: str,
        timeout_s: float,
        insecure: bool,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout_s = timeout_s
        self.ssl_context = None

        if insecure:
            self.ssl_context = ssl._create_unverified_context()

    def send(
        self,
        runtime: StationRuntime,
        payload: dict[str, Any],
    ) -> tuple[int, str]:
        config = runtime.config
        url = (
            f"{self.base_url}/api/v1/stations/"
            f"{quote(config.device_id, safe='-_.~')}/telemetry"
        )
        body = json.dumps(
            payload,
            separators=(",", ":"),
        ).encode("utf-8")

        request = urllib.request.Request(
            url=url,
            data=body,
            method="POST",
            headers={
                "Accept": "application/json",
                "Content-Type": "application/json",
                "X-Station-Token": config.token,
                "User-Agent": "ESP32-NTRIP-Simulator/2.1",
            },
        )

        try:
            with urllib.request.urlopen(
                request,
                timeout=self.timeout_s,
                context=self.ssl_context,
            ) as response:
                response_body = response.read().decode(
                    "utf-8",
                    errors="replace",
                )
                return response.status, response_body
        except urllib.error.HTTPError as error:
            return (
                error.code,
                error.read().decode("utf-8", errors="replace"),
            )
        except (urllib.error.URLError, TimeoutError) as error:
            return 0, str(error)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Simulate ESP32 base stations and hardware-faithful Raspberry Pi "
            "NTRIP rover bridges for the Laravel NTRIP system."
        )
    )
    parser.add_argument(
        "--base-url",
        default="http://ctuav-ntrip.local:8000",
        help="Laravel HTTP API URL.",
    )
    parser.add_argument(
        "--caster-host",
        default="ctuav-ntrip.local",
        help="Caster host used by simulated base Sources and per-station rovers.",
    )
    parser.add_argument("--caster-port", type=int, default=2101)
    parser.add_argument("--interval", type=float, default=2.0)
    parser.add_argument("--timeout", type=float, default=5.0)
    parser.add_argument(
        "--only",
        action="append",
        default=[],
        metavar="DEVICE_ID",
        help="Select one or more built-in station profiles.",
    )
    parser.add_argument("--once", action="store_true")
    parser.add_argument(
        "--no-rtcm",
        action="store_true",
        help="Disable Source streams while retaining telemetry and rover tests.",
    )
    parser.add_argument(
        "--rover-only",
        action="store_true",
        help="Disable ESP32 Source and telemetry; run only rover clients.",
    )
    parser.add_argument("--rtcm-file", type=Path)
    parser.add_argument("--replay-delay-ms", type=float, default=20.0)

    parser.add_argument(
        "--rovers-per-station",
        type=int,
        default=1,
        help=(
            "Create this many Pi-bridge-compatible rover clients per station. "
            "Default 1 gives the zero-argument 5-station + 5-rover preset."
        ),
    )
    parser.add_argument("--rover-username", default="")
    parser.add_argument("--rover-password", default="")
    parser.add_argument("--rover-start-delay", type=float, default=1.5)
    parser.add_argument("--rover-gga-interval", type=float, default=5.0)
    parser.add_argument(
        "--rover-rtcm-whitelist",
        default="",
        help="Comma-separated RTCM IDs. Empty forwards every valid frame.",
    )

    parser.add_argument(
        "--ntrip-client-config",
        type=Path,
        help=(
            "Load the deployed ntrip_cc config.conf and create a dedicated "
            "hardware-faithful rover client."
        ),
    )
    parser.add_argument(
        "--ntrip-client-count",
        type=int,
        default=1,
        help="Number of dedicated clients instantiated from config.conf.",
    )

    parser.add_argument(
        "--mavlink-output",
        choices=("none", "config", "udp", "serial"),
        default="none",
        help=(
            "Forward valid RTCM as MAVLink GPS_RTCM_DATA. 'config' reads the "
            "transport from --ntrip-client-config. Default none is safe for UI debug."
        ),
    )
    parser.add_argument("--mavlink-udp-host", default="127.0.0.1")
    parser.add_argument("--mavlink-udp-port", type=int, default=14550)
    parser.add_argument("--mavlink-serial-device", default="/dev/serial0")
    parser.add_argument("--mavlink-serial-baud", type=int, default=921600)
    parser.add_argument("--mavlink-sysid", type=int, default=255)
    parser.add_argument("--mavlink-compid", type=int, default=190)

    parser.add_argument("--debug-rover", action="store_true")
    parser.add_argument("--insecure", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def run_self_test() -> int:
    test_config = StationConfig(**DEFAULT_STATIONS[0])
    frames = [
        build_type_1005(
            test_config.station_id,
            test_config.latitude,
            test_config.longitude,
            test_config.altitude_m,
        )
    ]
    frames.extend(
        build_synthetic_rtcm_frame(
            message_type=message_type,
            station_id=test_config.station_id,
            sequence=index,
        )
        for index, message_type in enumerate((1074, 1084, 1094, 1124, 1230))
    )
    if not all(validate_rtcm_frame(frame) for frame in frames):
        print("ERROR: generated RTCM frame failed CRC validation.")
        return 1

    rover = RoverConfig(
        name="SELFTEST",
        ntrip_host="127.0.0.1",
        ntrip_port=2101,
        mountpoint="BASE",
        username="huy",
        password="123456",
        fixed_latitude=10.9801234,
        fixed_longitude=106.6745678,
        fixed_altitude_m=18.4,
    )
    expected_request = (
        "GET /BASE HTTP/1.0\r\n"
        "Host: 127.0.0.1\r\n"
        "Ntrip-Version: Ntrip/2.0\r\n"
        "User-Agent: NTRIP PiNtripBridge/1.0\r\n"
        "Authorization: Basic aHV5OjEyMzQ1Ng==\r\n\r\n"
    ).encode("ascii")
    if build_pi_bridge_handshake(rover) != expected_request:
        print("ERROR: Pi bridge HTTP handshake does not match ntrip.cc.")
        return 1

    fixed_time = time.struct_time((2026, 7, 17, 1, 2, 3, 0, 0, 0))
    gga = build_pi_bridge_gga(
        10.9801234, 106.6745678, 18.4, utc_time=fixed_time
    )
    if not gga.startswith(b"$GPGGA,010203,") or not gga.endswith(b"\r\n"):
        print("ERROR: GGA format does not match ntrip.cc.")
        return 1
    body, transmitted_checksum = gga[1:].strip().rsplit(b"*", 1)
    checksum = 0
    for byte in body:
        checksum ^= byte
    if transmitted_checksum != f"{checksum:02X}".encode("ascii"):
        print("ERROR: GGA checksum is invalid.")
        return 1

    runtime = RoverRuntime(rover)
    output = MavlinkGpsRtcmOutput(rover, runtime)
    # Exercise the exact fragmentation rules without opening an output device.
    short_payload = (
        bytes((0, len(frames[0])))
        + frames[0]
        + bytes(MAVLINK_GPS_RTCM_DATA_MAX_FIELD - len(frames[0]))
    )
    packet = build_mavlink2_packet(
        payload=short_payload,
        message_id=MAVLINK_MSG_ID_GPS_RTCM_DATA,
        packet_sequence=0,
        system_id=255,
        component_id=190,
        crc_extra=MAVLINK_GPS_RTCM_DATA_CRC_EXTRA,
    )
    if not validate_mavlink2_packet(packet, MAVLINK_GPS_RTCM_DATA_CRC_EXTRA):
        print("ERROR: MAVLink GPS_RTCM_DATA packet CRC is invalid.")
        return 1
    if len(packet) != 194:
        print(f"ERROR: unexpected MAVLink packet length: {len(packet)}")
        return 1

    global_position_payload = struct.pack(
        "<IiiiihhhH",
        1234,
        round(10.9801234 * 1e7),
        round(106.6745678 * 1e7),
        18400,
        1000,
        0,
        0,
        0,
        0,
    )
    global_position_packet = build_mavlink2_packet(
        payload=global_position_payload,
        message_id=MAVLINK_MSG_ID_GLOBAL_POSITION_INT,
        packet_sequence=1,
        system_id=1,
        component_id=1,
        crc_extra=MAVLINK_GLOBAL_POSITION_INT_CRC_EXTRA,
    )
    decoded_position = decode_global_position_int(global_position_packet)
    if decoded_position is None:
        print("ERROR: GLOBAL_POSITION_INT decoding failed.")
        return 1
    if abs(decoded_position[0] - 10.9801234) > 1e-7:
        print("ERROR: decoded MAVLink latitude is incorrect.")
        return 1
    del output

    print(
        "Hardware simulator self-test OK:\n"
        "  RTCM CRC:      1005, 1074, 1084, 1094, 1124, 1230\n"
        "  NTRIP client:  HTTP/1.0 + Basic auth + PiNtripBridge user-agent\n"
        "  GGA:           exact ntrip.cc shape and checksum\n"
        "  MAVLink:       GPS_RTCM_DATA output + GLOBAL_POSITION_INT input OK"
    )
    return 0


def main() -> int:
    args = parse_args()

    if args.self_test:
        return run_self_test()

    if args.interval <= 0 or args.timeout <= 0:
        print("ERROR: --interval and --timeout must be greater than 0.", file=sys.stderr)
        return 2
    if not 1 <= args.caster_port <= 65535:
        print("ERROR: --caster-port is invalid.", file=sys.stderr)
        return 2
    if args.replay_delay_ms <= 0:
        print("ERROR: --replay-delay-ms must be greater than 0.", file=sys.stderr)
        return 2
    if args.rovers_per_station < 0 or args.ntrip_client_count < 0:
        print("ERROR: rover counts cannot be negative.", file=sys.stderr)
        return 2
    if args.rover_start_delay < 0 or args.rover_gga_interval <= 0:
        print("ERROR: invalid rover timing.", file=sys.stderr)
        return 2
    if args.mavlink_output == "config" and args.ntrip_client_config is None:
        print(
            "ERROR: --mavlink-output=config requires --ntrip-client-config.",
            file=sys.stderr,
        )
        return 2

    try:
        rover_whitelist = parse_rtcm_whitelist(args.rover_rtcm_whitelist)
    except ValueError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2

    selected_ids = set(args.only)
    selected = [
        StationConfig(**item)
        for item in DEFAULT_STATIONS
        if not selected_ids or item["device_id"] in selected_ids
    ]
    if not selected:
        print("ERROR: No matching station profile.", file=sys.stderr)
        return 2

    real_frames = None
    if args.rtcm_file is not None:
        try:
            real_frames = load_rtcm_file(args.rtcm_file)
        except (OSError, ValueError) as error:
            print(f"ERROR: {error}", file=sys.stderr)
            return 2
        counts = Counter(rtcm_message_type(frame) for frame in real_frames)
        print(
            f"Loaded {len(real_frames)} valid RTCM frames: "
            + ", ".join(
                f"{message_type}={count}"
                for message_type, count in sorted(counts.items())
            )
        )

    rover_configs: list[RoverConfig] = []

    for station in selected:
        for rover_index in range(args.rovers_per_station):
            rover_configs.append(
                RoverConfig(
                    name=f"PI-{station.station_id:03d}-{rover_index + 1:02d}",
                    ntrip_host=args.caster_host,
                    ntrip_port=args.caster_port,
                    mountpoint=station.mountpoint,
                    username=args.rover_username,
                    password=args.rover_password,
                    fixed_latitude=station.latitude + (rover_index + 1) * 0.00001,
                    fixed_longitude=station.longitude + (rover_index + 1) * 0.00001,
                    fixed_altitude_m=station.altitude_m,
                    rtcm_whitelist=rover_whitelist,
                    mavlink_output=(
                        args.mavlink_output
                        if args.mavlink_output in {"none", "udp", "serial"}
                        else "none"
                    ),
                    mavlink_udp_host=args.mavlink_udp_host,
                    mavlink_udp_port=args.mavlink_udp_port,
                    mavlink_serial_device=args.mavlink_serial_device,
                    mavlink_serial_baud=args.mavlink_serial_baud,
                    mavlink_sysid=args.mavlink_sysid,
                    mavlink_compid=args.mavlink_compid,
                )
            )

    if args.ntrip_client_config is not None:
        try:
            for client_index in range(args.ntrip_client_count):
                rover_configs.append(
                    load_pi_bridge_config(
                        args.ntrip_client_config,
                        name=f"PI-CONFIG-{client_index + 1:02d}",
                        mavlink_output_override=args.mavlink_output,
                        udp_host_override=args.mavlink_udp_host,
                        udp_port_override=args.mavlink_udp_port,
                        serial_device_override=args.mavlink_serial_device,
                        serial_baud_override=args.mavlink_serial_baud,
                        sysid_override=args.mavlink_sysid,
                        compid_override=args.mavlink_compid,
                    )
                )
        except (OSError, ValueError) as error:
            print(f"ERROR: cannot load NTRIP client config: {error}", file=sys.stderr)
            return 2

    if args.rover_only and not rover_configs:
        print(
            "ERROR: --rover-only requires --rovers-per-station > 0 or "
            "--ntrip-client-config.",
            file=sys.stderr,
        )
        return 2

    serial_rovers = [
        config for config in rover_configs if config.mavlink_output == "serial"
    ]
    if len(serial_rovers) > 1:
        print(
            "ERROR: multiple rover instances cannot safely write the same serial "
            "MAVLink device. Use one client or UDP output.",
            file=sys.stderr,
        )
        return 2

    stop_event = threading.Event()
    station_runtimes = [StationRuntime(config=item) for item in selected]
    rover_runtimes = [RoverRuntime(config=item) for item in rover_configs]
    source_workers: list[NtripSourceWorker] = []
    rover_workers: list[NtripRoverWorker] = []

    def stop_handler(_signal_number: int, _frame: Any) -> None:
        stop_event.set()

    signal.signal(signal.SIGINT, stop_handler)
    signal.signal(signal.SIGTERM, stop_handler)

    if not args.rover_only and not args.no_rtcm:
        source_workers = [
            NtripSourceWorker(
                runtime=runtime,
                caster_host=args.caster_host,
                caster_port=args.caster_port,
                timeout_s=args.timeout,
                stop_event=stop_event,
                real_frames=real_frames,
                replay_delay_s=args.replay_delay_ms / 1000.0,
            )
            for runtime in station_runtimes
        ]
        for worker in source_workers:
            worker.start()

    rover_workers = [
        NtripRoverWorker(
            runtime=runtime,
            timeout_s=args.timeout,
            stop_event=stop_event,
            start_delay_s=args.rover_start_delay,
            gga_interval_s=args.rover_gga_interval,
            debug=args.debug_rover,
        )
        for runtime in rover_runtimes
    ]
    for worker in rover_workers:
        worker.start()

    sender = TelemetrySender(
        base_url=args.base_url,
        timeout_s=args.timeout,
        insecure=args.insecure,
    )

    print("=" * 72)
    print("CTUAV NTRIP FULL-FLOW SIMULATOR")
    print(
        f"Preset: {len(station_runtimes)} base stations + "
        f"{len(rover_runtimes)} rover clients"
    )
    print(
        f"Expected live NTRIP sessions after connection: "
        f"{len(source_workers) + len(rover_workers)}"
    )
    print("=" * 72)
    print(f"HTTP telemetry: {args.base_url}")
    print(f"NTRIP Source:   {args.caster_host}:{args.caster_port}")
    print(
        "Stations:       "
        + (
            ", ".join(runtime.config.device_id for runtime in station_runtimes)
            if not args.rover_only
            else "disabled"
        )
    )
    print(f"Rover clients:  {len(rover_runtimes)}")
    for runtime in rover_runtimes:
        config = runtime.config
        auth = config.username if config.username else "anonymous"
        if config.mavlink_output != "none":
            gga = (
                "MAVLink position, then fixed fallback"
                if config.fixed_latitude is not None and config.fixed_longitude is not None
                else "MAVLink vehicle position"
            )
        else:
            gga = (
                "fixed fallback"
                if config.fixed_latitude is not None and config.fixed_longitude is not None
                else "disabled (no MAVLink position or fixed fallback)"
            )
        whitelist = (
            ",".join(str(item) for item in sorted(config.rtcm_whitelist))
            if config.rtcm_whitelist
            else "all"
        )
        print(
            f"  [{config.name}] {config.ntrip_host}:{config.ntrip_port}/"
            f"{config.mountpoint} auth={auth} gga={gga} "
            f"rtcm={whitelist} mavlink={config.mavlink_output}"
        )

    if args.once and (source_workers or rover_workers):
        stop_event.wait(max(1.25, args.rover_start_delay + 1.25))

    try:
        while not stop_event.is_set():
            cycle_started = time.monotonic()

            if not args.rover_only:
                for runtime in station_runtimes:
                    payload = runtime.snapshot(
                        caster_host=args.caster_host,
                        caster_port=args.caster_port,
                        management_url=args.base_url,
                    )
                    status, response_body = sender.send(runtime, payload)
                    rtcm = payload["rtcm"]
                    state = "UP" if rtcm["connected"] else "DOWN"
                    if 200 <= status < 300:
                        print(
                            f"[{runtime.config.device_id}] HTTP={status} "
                            f"SOURCE={state} RTCM={rtcm['upload_bps']}bps "
                            f"frames={rtcm['frames_valid']} crc={rtcm['crc_errors']}"
                        )
                    else:
                        message = response_body.strip().replace("\n", " ")
                        print(
                            f"[{runtime.config.device_id}] HTTP ERROR {status}: {message}",
                            file=sys.stderr,
                        )

            for runtime in rover_runtimes:
                rover = runtime.snapshot()
                age = f"{rover['age_ms']}ms" if rover["age_ms"] is not None else "-"
                error = f" error={rover['last_error']}" if rover["last_error"] else ""
                print(
                    f"[{rover['name']}] status={rover['status']} "
                    f"mount={rover['mountpoint']} RTCM={rover['download_bps']}bps "
                    f"frames={rover['frames_valid']} crc={rover['crc_errors']} "
                    f"forwarded={rover['frames_forwarded']} "
                    f"mavpkt={rover['mavlink_packets_sent']} gga={rover['gga_sent']} "
                    f"age={age}{error}"
                )

            if args.once:
                break

            elapsed = time.monotonic() - cycle_started
            stop_event.wait(max(0.0, args.interval - elapsed))
    finally:
        stop_event.set()
        for worker in source_workers:
            worker.join(timeout=args.timeout + 17.0)
        for worker in rover_workers:
            worker.join(timeout=args.timeout + 17.0)

    print("Simulator stopped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
